-- AlterTable
ALTER TABLE `Kindertageseinrichtung` MODIFY `TRAEGER` VARCHAR(255) NULL,
    MODIFY `KURZBEZEICHNUNG` VARCHAR(255) NULL,
    MODIFY `STRASSE` VARCHAR(255) NULL,
    MODIFY `STRSCHL` VARCHAR(255) NULL,
    MODIFY `HAUSBEZ` VARCHAR(255) NULL,
    MODIFY `PLZ` VARCHAR(255) NULL,
    MODIFY `ORT` VARCHAR(255) NULL,
    MODIFY `FAX` VARCHAR(255) NULL,
    MODIFY `EMAIL` VARCHAR(255) NULL;
