-- AlterTable
ALTER TABLE `Address` MODIFY `postalCode` VARCHAR(50) NOT NULL;

-- AlterTable
ALTER TABLE `Entity` MODIFY `STANDORTTYP` CHAR(50) NULL,
    MODIFY `BEZUGNR` CHAR(50) NULL,
    MODIFY `GlobalID` VARCHAR(50) NOT NULL;

-- AlterTable
ALTER TABLE `Jugendberufshilfe` MODIFY `PLZ` VARCHAR(50) NOT NULL,
    MODIFY `ORT` VARCHAR(50) NOT NULL,
    MODIFY `FAX` VARCHAR(50) NULL;

-- AlterTable
ALTER TABLE `Kindertageseinrichtung` MODIFY `STRASSE` VARCHAR(200) NULL,
    MODIFY `HAUSBEZ` VARCHAR(50) NULL;

-- AlterTable
ALTER TABLE `Schule` MODIFY `STANDORTTYP` CHAR(50) NULL,
    MODIFY `ORT` VARCHAR(50) NULL,
    MODIFY `TELEFON` VARCHAR(50) NULL,
    MODIFY `FAX` VARCHAR(50) NULL,
    MODIFY `BEZUGNR` CHAR(50) NULL;

-- AlterTable
ALTER TABLE `Schulsozialarbeit` MODIFY `PLZ` VARCHAR(50) NOT NULL,
    MODIFY `ORT` VARCHAR(50) NOT NULL,
    MODIFY `FAX` VARCHAR(50) NULL;
