-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `User_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Address` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `street` VARCHAR(255) NOT NULL,
    `street2` VARCHAR(255) NULL,
    `city` VARCHAR(100) NOT NULL,
    `state` VARCHAR(100) NULL,
    `postalCode` VARCHAR(20) NOT NULL,
    `country` VARCHAR(100) NOT NULL,
    `userId` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Address_userId_key`(`userId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Schule` (
    `OBJECTID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID` INTEGER NOT NULL,
    `TYP` INTEGER NOT NULL,
    `ART` VARCHAR(45) NOT NULL,
    `STANDORTTYP` CHAR(1) NOT NULL,
    `BEZEICHNUNG` VARCHAR(255) NULL,
    `BEZEICHNUNGZUSATZ` VARCHAR(255) NULL,
    `KURZBEZEICHNUNG` VARCHAR(50) NULL,
    `STRASSE` VARCHAR(200) NULL,
    `PLZ` VARCHAR(200) NULL,
    `ORT` VARCHAR(10) NULL,
    `TELEFON` VARCHAR(20) NULL,
    `FAX` VARCHAR(20) NULL,
    `EMAIL` VARCHAR(55) NULL,
    `PROFILE` VARCHAR(255) NULL,
    `SPRACHEN` VARCHAR(255) NULL,
    `WWW` VARCHAR(255) NULL,
    `TRAEGER` VARCHAR(60) NULL,
    `TRAEGERTYP` INTEGER NOT NULL,
    `BEZUGNR` CHAR(3) NOT NULL,
    `GEBIETSARTNUMMER` INTEGER NOT NULL,
    `SNUMMER` DOUBLE NOT NULL,
    `NUMMER` DOUBLE NOT NULL,
    `GlobalID` VARCHAR(38) NOT NULL,
    `CreationDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Creator` VARCHAR(128) NOT NULL,
    `EditDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Editor` VARCHAR(128) NOT NULL,
    `x` DOUBLE NOT NULL,
    `y` DOUBLE NOT NULL,

    PRIMARY KEY (`OBJECTID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Kindertageseinrichtung` (
    `OBJECTID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID` INTEGER NOT NULL,
    `TRAEGER` VARCHAR(50) NOT NULL,
    `BEZEICHNUNG` VARCHAR(100) NOT NULL,
    `KURZBEZEICHNUNG` VARCHAR(100) NOT NULL,
    `STRASSE` VARCHAR(24) NOT NULL,
    `STRSCHL` VARCHAR(50) NOT NULL,
    `HAUSBEZ` VARCHAR(5) NOT NULL,
    `PLZ` VARCHAR(50) NOT NULL,
    `ORT` VARCHAR(50) NOT NULL,
    `HORT` INTEGER NOT NULL,
    `KITA` INTEGER NOT NULL,
    `URL` VARCHAR(255) NULL,
    `TELEFON` VARCHAR(255) NULL,
    `FAX` VARCHAR(50) NULL,
    `EMAIL` VARCHAR(50) NULL,
    `BARRIEREFREI` INTEGER NOT NULL,
    `INTEGRATIV` INTEGER NOT NULL,
    `x` DOUBLE NOT NULL,
    `y` DOUBLE NOT NULL,

    PRIMARY KEY (`OBJECTID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Schulsozialarbeit` (
    `OBJECTID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID` INTEGER NOT NULL,
    `TRAEGER` VARCHAR(255) NOT NULL,
    `LEISTUNGEN` VARCHAR(255) NOT NULL,
    `BEZEICHNUNG` VARCHAR(255) NULL,
    `KURZBEZEICHNUNG` VARCHAR(255) NULL,
    `STRASSE` VARCHAR(255) NULL,
    `PLZ` VARCHAR(5) NOT NULL,
    `ORT` VARCHAR(10) NOT NULL,
    `TELEFON` VARCHAR(50) NULL,
    `EMAIL` VARCHAR(255) NULL,
    `FAX` VARCHAR(20) NULL,
    `x` DOUBLE NOT NULL,
    `y` DOUBLE NOT NULL,

    PRIMARY KEY (`OBJECTID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Jugendberufshilfe` (
    `OBJECTID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID` INTEGER NOT NULL,
    `TRAEGER` VARCHAR(255) NOT NULL,
    `LEISTUNGEN` VARCHAR(255) NOT NULL,
    `BEZEICHNUNG` VARCHAR(255) NULL,
    `KURZBEZEICHNUNG` VARCHAR(255) NULL,
    `STRASSE` VARCHAR(255) NULL,
    `PLZ` VARCHAR(5) NOT NULL,
    `ORT` VARCHAR(10) NOT NULL,
    `TELEFON` VARCHAR(50) NULL,
    `EMAIL` VARCHAR(255) NULL,
    `FAX` VARCHAR(20) NULL,
    `x` DOUBLE NOT NULL,
    `y` DOUBLE NOT NULL,

    PRIMARY KEY (`OBJECTID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Entity` (
    `OBJECTID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID` INTEGER NOT NULL,
    `EntityType` ENUM('Schule', 'Kindertageseinrichtung', 'Schulsozialarbeit', 'Jugendberufshilfe') NOT NULL,
    `TRAEGER` VARCHAR(255) NOT NULL,
    `LEISTUNGEN` VARCHAR(255) NULL,
    `ART` VARCHAR(45) NULL,
    `STANDORTTYP` CHAR(1) NULL,
    `BEZEICHNUNG` VARCHAR(255) NULL,
    `BEZEICHNUNGZUSATZ` VARCHAR(255) NULL,
    `KURZBEZEICHNUNG` VARCHAR(255) NULL,
    `STRASSE` VARCHAR(255) NULL,
    `PLZ` VARCHAR(50) NULL,
    `ORT` VARCHAR(50) NULL,
    `TELEFON` VARCHAR(255) NULL,
    `FAX` VARCHAR(50) NULL,
    `EMAIL` VARCHAR(255) NULL,
    `PROFILE` VARCHAR(255) NULL,
    `SPRACHEN` VARCHAR(255) NULL,
    `WWW` VARCHAR(255) NULL,
    `TRAEGERTYP` INTEGER NULL,
    `BEZUGNR` CHAR(3) NULL,
    `GEBIETSARTNUMMER` INTEGER NULL,
    `SNUMMER` DOUBLE NULL,
    `NUMMER` DOUBLE NULL,
    `GlobalID` VARCHAR(38) NOT NULL,
    `CreationDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Creator` VARCHAR(128) NOT NULL,
    `EditDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Editor` VARCHAR(128) NOT NULL,
    `HORT` INTEGER NULL,
    `KITA` INTEGER NULL,
    `BARRIEREFREI` INTEGER NULL,
    `INTEGRATIV` INTEGER NULL,
    `x` DOUBLE NOT NULL,
    `y` DOUBLE NOT NULL,

    PRIMARY KEY (`OBJECTID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Address` ADD CONSTRAINT `Address_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
